# Generated by Django 5.2.3 on 2025-06-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_order_date_delivered_order_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='date_cancelled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
