# Generated by Django 5.2.3 on 2025-06-23 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_order_cancelled_order_date_cancelled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cancelled',
            new_name='viewed_by_admin',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_cancelled',
        ),
    ]
